### ISSUE TITLE
Live Data Display

### ISSUE THREAD

**Issue by F1nx** [F1nx/packet-airport#4]
The main improvement of this fork revolves around finding a JavaScript method to keep the HTML code live without messing up the packet data.

Off the top of my head, I think it would be good if we restarted the animation script(s) at the end of the first cycle, loading in an entirely new file of packet data each time. The main obstacle, here, is finding a way to activate the other files, and cleaning up everything after the page is closed.

**Comment by ForgivenNin** [comment]
Looks like for BASH, the `tails -f` command could help in adopting the new packets added to the file. Then, we use JavaScript to await new data to come in, restarting the display cycle.

**Comment by ForgivenNin** [comment]
Could also either use the HTML `<form>` element to trigger a file or have a timer for the shell script to add the new packet file only for JavaScript to change from `data.js` to something like `data1.js`.

**Comment by fr33roam3r** [comment]
Use JavaScript to refresh the page and have Python or Bash to limit the length of the information file. This can be done in a similar fashion to working with an array by pushing an item while removing the first one on the other side.

**Comment by F1nx** [comment]
Solve #10 before continuing.

**Comment by F1nx** [comment]
Automatically figure out the latency and correct the timings to account for it. The dump timestamps show the send time of sent packets and the received time of received packets, so the timings for received packets have to be adjusted backwards.
